# subir serviço do gateway

services:
  gateway:
    build: ./gateway
    ports:
      - "9000:9000"
    networks:
      - app-network
    depends_on:
      - rabbitmq
  account_service:
    build: ./account_service/docker-build
    networks:
      - app-network
    depends_on:
      - db_account
      - redis
  transaction_service:
    build: ./transaction_service/docker-build
    networks:
      - app-network
    depends_on:
      - redis
      - rabbitmq
      - gateway
  report_service:
    build: ./report_service/docker-build
    networks:
      - app-network
    depends_on:
      - db_report
      - rabbitmq
      - gateway
  db_account:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
  db_report:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    networks:
      - app-network
  redis:
    image: redis:6.0.9-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data
  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local

